#!/bin/bash
#---ARRAYS: BASH_SETSOFCMDS_ARR
#column 1: directory (e.g. bin, sbin)
#column 2: filename (e.g. apt-get, cat)
BASH_SETSOFCMDS_ARR=("bin,apt-get" \
    "bin,cat" \
    "bin,chmod" \
    "bin,dpkg" \
    "bin,grep" \
    "bin,mkdir" \
    "bin,rm" \
    "bin,sed" \
    "bin,sleep" \
    "usr,bin,systemctl" \
    "bin,tee" \
    "bin,test" \
    "bin,touch" \
    "sbin,brctl" \
    "sbin,ip" \
    "sbin,iptables" \
    "sbin,ip6tables" \
    "sbin,iptables-restore" \
    "sbin,ip6tables-restore" \
    "sbin,iptables-save" \
    "sbin,ip6tables-save" \
    "sbin,iw" \
    "sbin,iwlist" \
    "sbin,iwconfig" \
    "bin,ls" \
    "sbin,modprobe" \
    "sbin,netplan" \
    "sbin,sysctl" \
    "sbin,ufw" \
    "sbin,wpa_supplicant" \
    "usr,bin,cp"
)

DNSMASQ_FULLPATH_ARR=( \
    "/run/dnsmasq" \
    "/etc/dnsmasq.conf" \
    "/etc/insserv.conf.d/dnsmasq" \
    "/etc/dnsmasq.d" \
    "/etc/default/dnsmasq" \
    "/etc/dbus-1/system.d/dnsmasq.conf" \
    "/etc/resolvconf/update.d/dnsmasq" \
    "/etc/init.d/dnsmasq" \
    "/var/cache/apt/archives/dnsmasq-base_2.80-1.1ubuntu1.6_armhf.deb" \
    "/var/cache/apt/archives/dnsmasq_2.80-1.1ubuntu1.6_all.deb" \
    "/var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/dnsmasq.service" \
    "/var/lib/systemd/deb-systemd-helper-enabled/dnsmasq.service.dsh-also" \
    "/var/lib/dpkg/info/dnsmasq-base.postrm" \
    "/var/lib/dpkg/info/dnsmasq-base.list" \
    "/var/lib/dpkg/info/dnsmasq-base.md5sums" \
    "/var/lib/dpkg/info/dnsmasq-base.conffiles" \
    "/var/lib/dpkg/info/dnsmasq-base.postinst" \
    "/var/lib/dpkg/info/dnsmasq.postrm" \
    "/var/lib/dpkg/info/dnsmasq.list" \
    "/var/lib/dpkg/info/dnsmasq.md5sums" \
    "/var/lib/dpkg/info/dnsmasq.prerm" \
    "/var/lib/dpkg/info/dnsmasq.conffiles" \
    "/var/lib/dpkg/info/dnsmasq.postinst" \
    "/usr/lib/systemd/system/dnsmasq.service" \
    "/usr/lib/tmpfiles.d/dnsmasq.conf" \
    "/usr/lib/resolvconf/dpkg-event.d/dnsmasq" \
    "/usr/share/dnsmasq" \
    "/usr/share/vim/vim81/syntax/dnsmasq.vim" \
    "/usr/share/doc/dnsmasq-base" \
    "/usr/share/doc/dnsmasq" \
    "/usr/share/dnsmasq-base" \
    "/usr/sbin/dnsmasq" \
)

HOSTAPD_FULLPATH_ARR=( \
    "/usr/sbin/hostapd_cli" \
    "/usr/sbin/hostapd" \
    "/usr/lib/systemd/system/hostapd@.service" \
    "/usr/lib/systemd/system/hostapd.service" \
    "/usr/share/lintian/overrides/hostapd" \
    "/usr/share/doc/hostapd" \
    "/var/cache/apt/archives/hostapd_2%3a2.9-1ubuntu4.3_armhf.deb" \
    "/var/lib/dpkg/info/hostapd.postinst" \
    "/var/lib/dpkg/info/hostapd.list" \
    "/var/lib/dpkg/info/hostapd.postrm" \
    "/var/lib/dpkg/info/hostapd.prerm" \
    "/var/lib/dpkg/info/hostapd.md5sums" \
    "/var/lib/dpkg/info/hostapd.conffiles" \
    "/var/lib/systemd/deb-systemd-helper-enabled/hostapd.service.dsh-also" \
    "/etc/default/hostapd" \
    "/etc/hostapd/ifupdown.sh" \
    "/etc/init.d/hostapd" \
    "/etc/network/if-post-down.d/hostapd" \
    "/etc/network/if-pre-up.d/hostapd" \
)

WPA_SUPPLICANT_FULLPATH_ARR=( \
    "/etc/network/if-post-down.d/wpasupplicant" \
    "/etc/network/if-pre-up.d/wpasupplicant" \
    "/etc/network/if-down.d/wpasupplicant" \
    "/etc/network/if-up.d/wpasupplicant" \
    "/etc/ifplugd/action.d/action_wpa" \
    "/etc/dbus-1/system.d/wpa_supplicant.conf" \
    "/etc/wpa_supplicant" \
    "/etc/wpa_supplicant/action_wpa.sh" \
    "/usr/sbin/wpa_cli" \
    "/usr/sbin/wpa_supplicant" \
    "/usr/sbin/wpa_action" \
    "/usr/lib/systemd/system/wpa_supplicant-wired@.service" \
    "/usr/lib/systemd/system/wpa_supplicant.service" \
    "/usr/lib/systemd/system/wpa_supplicant@.service" \
    "/usr/lib/systemd/system/wpa_supplicant-nl80211@.service" \
    "/usr/lib/pm-utils/sleep.d/60_wpa_supplicant" \
    "/usr/share/lintian/overrides/wpasupplicant" \
    "/usr/share/dbus-1/system-services/fi.w1.wpa_supplicant1.service" \
    "/usr/share/doc/wpasupplicant" \
    "/usr/share/doc/wpa_supplicant" \
    "/usr/bin/wpa_passphrase" \
    "/var/lib/systemd/deb-systemd-helper-enabled/wpa_supplicant.service.dsh-also" \
)


#---ENUM: accepted_rejected
ACCEPTED="0"
REJECTED="1"
UNSET="255"

#---ENUM: pl_wln_bss_modes
#Meaning of 'PL_WLN_BSS_MODE_INFRASTRUCTURE':
#   In 'associate' method, connect to an SSID as a client.
#   In 'scanresultbssmode' property, whether the SSID is in 'Infrastructure' mode.
PL_WLN_BSS_MODE_INFRASTRUCTURE=0
#Meaning of 'PL_WLN_BSS_MODE_ADHOC':
#   In 'scanresultbssmode' property, whether the SSID is in 'Ad-hoc' mode.
PL_WLN_BSS_MODE_ADHOC=1
#Meaning of 'PL_WLN_BSS_MODE_ACCESSPOINT':
#   In 'networkstart' method, whether to run the LTPP3-G2 as an 'Accesspoint'
PL_WLN_BSS_MODE_ACCESSPOINT=2
#Meaning of 'PL_WLN_BSS_MODE_ROUTER':
#   In 'networkstart' method, whether to run the LTPP3-G2 as a 'Router'
PL_WLN_BSS_MODE_ROUTER=3
#Meaning of 'PL_WLN_BSS_MODE_INFRASTRUCTURE':
#   In 'scanresultbssmode' property, indicates that the mode is not known.
PL_WLN_BSS_MODE_UNKNOWN=255

#---ENUM: pl_wln_wpa_unicast_multicast
PL_WLN_WPA_CAST_UNICAST=0
PL_WLN_WPA_CAST_MULTICAST=1

#---ENUM: pl_wln_gateway_intfset
PL_WLN_GATEWAY_INTFSET_ETH0=0
PL_WLN_GATEWAY_INTFSET_ETH1=1
PL_WLN_GATEWAY_INTFSET_UNSET=255

#---ENUM: pl_wln_domains
PL_WLN_DOMAIN_AG=0
PL_WLN_DOMAIN_AR=1
PL_WLN_DOMAIN_AW=2
PL_WLN_DOMAIN_AU=3
PL_WLN_DOMAIN_AT=4
PL_WLN_DOMAIN_BS=5
PL_WLN_DOMAIN_BB=6
PL_WLN_DOMAIN_BM=7
PL_WLN_DOMAIN_BR=8
PL_WLN_DOMAIN_BE=9
PL_WLN_DOMAIN_BG=10
PL_WLN_DOMAIN_CA=11
PL_WLN_DOMAIN_KY=12
PL_WLN_DOMAIN_CL=13
PL_WLN_DOMAIN_CN=14
PL_WLN_DOMAIN_CO=15
PL_WLN_DOMAIN_CR=16
PL_WLN_DOMAIN_CY=17
PL_WLN_DOMAIN_CZ=18
PL_WLN_DOMAIN_DK=19
PL_WLN_DOMAIN_DO=20
PL_WLN_DOMAIN_EC=21
PL_WLN_DOMAIN_SV=22
PL_WLN_DOMAIN_FI=23
PL_WLN_DOMAIN_FR=24
PL_WLN_DOMAIN_DE=25
PL_WLN_DOMAIN_GR=26
PL_WLN_DOMAIN_GU=27
PL_WLN_DOMAIN_GT=28
PL_WLN_DOMAIN_HT=29
PL_WLN_DOMAIN_HN=30
PL_WLN_DOMAIN_HK=31
PL_WLN_DOMAIN_HU=32
PL_WLN_DOMAIN_IS=33
PL_WLN_DOMAIN_IN=34
PL_WLN_DOMAIN_ID=35
PL_WLN_DOMAIN_IE=36
PL_WLN_DOMAIN_IL=37
PL_WLN_DOMAIN_IT=38
PL_WLN_DOMAIN_JP=39
PL_WLN_DOMAIN_JO=40
PL_WLN_DOMAIN_LV=41
PL_WLN_DOMAIN_LI=42
PL_WLN_DOMAIN_LT=43
PL_WLN_DOMAIN_LU=44
PL_WLN_DOMAIN_MY=45
PL_WLN_DOMAIN_MT=46
PL_WLN_DOMAIN_MA=47
PL_WLN_DOMAIN_MX=48
PL_WLN_DOMAIN_NL=49
PL_WLN_DOMAIN_NZ=50
PL_WLN_DOMAIN_NO=51
PL_WLN_DOMAIN_PE=52
PL_WLN_DOMAIN_PT=53
PL_WLN_DOMAIN_PL=54
PL_WLN_DOMAIN_RO=55
PL_WLN_DOMAIN_RU=56
PL_WLN_DOMAIN_SA=57
PL_WLN_DOMAIN_CS=58
PL_WLN_DOMAIN_SG=59
PL_WLN_DOMAIN_SK=60
PL_WLN_DOMAIN_SI=61
PL_WLN_DOMAIN_ZA=62
PL_WLN_DOMAIN_KR=63
PL_WLN_DOMAIN_ES=64
PL_WLN_DOMAIN_SE=65
PL_WLN_DOMAIN_CH=66
PL_WLN_DOMAIN_TW=67
PL_WLN_DOMAIN_TR=68
PL_WLN_DOMAIN_GB=69
PL_WLN_DOMAIN_UA=70
PL_WLN_DOMAIN_AE=71
PL_WLN_DOMAIN_US=72
PL_WLN_DOMAIN_VE=73

#---ENUM: pl_wln_hostapd_auth_algs
PL_WLN_HOSTAPD_AUTH_ALG_1=1
PL_WLN_HOSTAPD_AUTH_ALG_2=2
PL_WLN_HOSTAPD_AUTH_ALG_3=3

#---ENUM: pl_wln_phy_modes
PL_WLN_PHY_MODE_2G_LEGACY=0
PL_WLN_PHY_MODE_2G=1
PL_WLN_PHY_MODE_5G=2
PL_WLN_PHY_MODE_NULL=255

#---ENUM: pl_wln_wep_modes
PL_WLN_WEP_MODE_DISABLED=0
PL_WLN_WEP_MODE_64=1
PL_WLN_WEP_MODE_128=2

#---ENUM: pl_wln_wpa_modes
PL_WLN_WPA_DISABLED=0
PL_WLN_WPA_WPA1_PSK=1
PL_WLN_WPA_WPA2_PSK=2

#---ENUM: pl_wln_wpa_algorithms (modified)
PL_WLN_WPA_ALGORITHM_TKIP=0
PL_WLN_WPA_ALGORITHM_AES=1
PL_WLN_WPA_ALGORITHM_TKIP_AES=2

#---ENUM: pl_wln_association_states
PL_WLN_NOT_ASSOCIATED=0
PL_WLN_ASSOCIATED=1     #infrastructure
PL_WLN_OWN_NETWORK=2    #router or accesspoint

#---ENUM (PRIVATE): pl_wln_signaltype
PL_WLN_SIGNALTYPE_RSSI=0
PL_WLN_SIGNALTYPE_PERC=1

#---MACROS: SERVICES
WLN_SERVICE_INPUTARG_INFRASTRUCTURE="infrastructure"
WLN_SERVICE_INPUTARG_ACCESSPOINT="accesspoint"
WLN_SERVICE_INPUTARG_ROUTER="router"

#---MACROS: COLOR CONSTANTS (WILL NOT BE USED)
WLN_RESETCOLOR=$'\e[0m'
WLN_LIGHTRED=$'\e[1;31m'
WLN_ORANGE=$'\e[30;38;5;209m'
WLN_LIGHTBLUE=$'\e[30;38;5;45m'
WLN_LIGHTGREY=$'\e[30;38;5;246m'
WLN_LIGHTGREEN=$'\e[30;38;5;71m'
WLN_SOFLIGHTRED=$'\e[30;38;5;131m'
WLN_YELLOW=$'\e[1;33m'

#---MACROS: COUNTRY-CODE
WLN_DOMAINCODE_00="00"
WLN_DOMAINCODE_AG="AG"
WLN_DOMAINCODE_AR="AR"
WLN_DOMAINCODE_AW="AW"
WLN_DOMAINCODE_AU="AU"
WLN_DOMAINCODE_AT="AT"
WLN_DOMAINCODE_BS="BS"
WLN_DOMAINCODE_BB="BB"
WLN_DOMAINCODE_BM="BM"
WLN_DOMAINCODE_BR="BR"
WLN_DOMAINCODE_BE="BE"
WLN_DOMAINCODE_BG="BG"
WLN_DOMAINCODE_CA="CA"
WLN_DOMAINCODE_KY="KY"
WLN_DOMAINCODE_CL="CL"
WLN_DOMAINCODE_CN="CN"
WLN_DOMAINCODE_CO="CO"
WLN_DOMAINCODE_CR="CR"
WLN_DOMAINCODE_CY="CY"
WLN_DOMAINCODE_CZ="CZ"
WLN_DOMAINCODE_DK="DK"
WLN_DOMAINCODE_DO="DO"
WLN_DOMAINCODE_EC="EC"
WLN_DOMAINCODE_SV="SV"
WLN_DOMAINCODE_FI="FI"
WLN_DOMAINCODE_FR="FR"
WLN_DOMAINCODE_DE="DE"
WLN_DOMAINCODE_GR="GR"
WLN_DOMAINCODE_GU="GU"
WLN_DOMAINCODE_GT="GT"
WLN_DOMAINCODE_HT="HT"
WLN_DOMAINCODE_HN="HN"
WLN_DOMAINCODE_HK="HK"
WLN_DOMAINCODE_HU="HU"
WLN_DOMAINCODE_IS="IS"
WLN_DOMAINCODE_IN="IN"
WLN_DOMAINCODE_ID="ID"
WLN_DOMAINCODE_IE="IE"
WLN_DOMAINCODE_IL="IL"
WLN_DOMAINCODE_IT="IT"
WLN_DOMAINCODE_JP="JP"
WLN_DOMAINCODE_JO="JO"
WLN_DOMAINCODE_LV="LV"
WLN_DOMAINCODE_LI="LI"
WLN_DOMAINCODE_LT="LT"
WLN_DOMAINCODE_LU="LU"
WLN_DOMAINCODE_MY="MY"
WLN_DOMAINCODE_MT="MT"
WLN_DOMAINCODE_MA="MA"
WLN_DOMAINCODE_MX="MX"
WLN_DOMAINCODE_NL="NL"
WLN_DOMAINCODE_NZ="NZ"
WLN_DOMAINCODE_NO="NO"
WLN_DOMAINCODE_PE="PE"
WLN_DOMAINCODE_PT="PT"
WLN_DOMAINCODE_PL="PL"
WLN_DOMAINCODE_RO="RO"
WLN_DOMAINCODE_RU="RU"
WLN_DOMAINCODE_SA="SA"
WLN_DOMAINCODE_CS="CS"
WLN_DOMAINCODE_SG="SG"
WLN_DOMAINCODE_SK="SK"
WLN_DOMAINCODE_SI="SI"
WLN_DOMAINCODE_ZA="ZA"
WLN_DOMAINCODE_KR="KR"
WLN_DOMAINCODE_ES="ES"
WLN_DOMAINCODE_SE="SE"
WLN_DOMAINCODE_CH="CH"
WLN_DOMAINCODE_TW="TW"
WLN_DOMAINCODE_TR="TR"
WLN_DOMAINCODE_GB="GB"
WLN_DOMAINCODE_UA="UA"
WLN_DOMAINCODE_AE="AE"
WLN_DOMAINCODE_US="US"
WLN_DOMAINCODE_VE="VE"

#---MACROS: COMMAND
WLN_NETPLAN_APPLY="netplan apply"
WLN_SYSCTL_P="sysctl -p"

WLN_DISABLE="disable"
WLN_ENABLE="enable"
# WLN_INSTALL="install"
WLN_ISACTIVE="is-active"
WLN_ISENABLED="is-enabled"
WLN_START="start"
WLN_STOP="stop"

WLN_DOWN="down"
WLN_UP="up"

#---MACROS: COUNTER
WLN_CONN_RETRY_MAX=3
WLN_CONN_STATUS_CHECK_CTR_MAX=30
WLN_IPADDR_CTR_MAX=10
#This timestamp difference (in seconds) is used in function 'WLN_enabled'.
#(new) - (old) timestamp < WLN_TIMESTAMPSEC_DIFF_MAX -> use the BACKED UP 'WLN_intfstates_ctx__enabled' value
#(new) - (old) timestamp > WLN_TIMESTAMPSEC_DIFF_MAX -> determine the NEW 'WLN_intfstates_ctx__enabled' value
WLN_TIMESTAMPSEC_DIFF_MAX=5 

WLN_DNSMASQ_SERVICE_RETRY_MAX=1
WLN_HOSTAPD_NG_DAEMON_RUN_RETRY_MAX=3
WLN_INTFSTATESET_RETRY_MAX=10
WLN_IPTABLES_SERVICE_RETRY_MAX=1
WLN_IW_RETRY_MAX=3
WLN_SYSTEMCTL_START_SERVICE_RETRY_MAX=3
WLN_TXBYTES_VALIDATE_RETRY_MAX=3

#---MACROS: DNSMASQ
WLN_DNSMASQ_LEASETTIME="12h"

#---MACROS: HEX
WLN_FOURBACKSLASHES_ASTERISK_HEX="\\\\x2A"
# WLN_FOURBACKSLASHES_HASH_HEX="\\\\x23"
WLN_FOURBACKSLASHES_SLASH_HEX="\\\\x2F"
WLN_FOURBACKSLASHES_SPACE_HEX="\\\\x20"
WLN_SIXTEENBACKSLASHES_ASTERISK_HEX="\\\\\\\\\\\\\\\\x2A"
WLN_SIXTEENBACKSLASHES_SLASH_HEX="\\\\\\\\\\\\\\\\x2F"
WLN_SIXTEENBACKSLASHES_SPACE_HEX="\\\\\\\\\\\\\\\\x20"

#---MACROS: HOSTAPD
WLN_HOSTAPD_CHANNEL_0=0
WLN_HOSTAPD_DRIVER="nl80211"
WLN_HOSTAPD_HWMODE_A="a"
WLN_HOSTAPD_HWMODE_B="b"
WLN_HOSTAPD_HWMODE_G="g"
WLN_HOSTAPD_IEEE80211AC_ENABLE=1
WLN_HOSTAPD_IEEE80211N_ENABLE=1
WLN_HOSTAPD_SSID_AP="LTPP3G2-AP"
WLN_HOSTAPD_SSID_AP_B="${WLN_HOSTAPD_SSID_AP}(B)"
WLN_HOSTAPD_SSID_AP_GN="${WLN_HOSTAPD_SSID_AP}(G/N)"
WLN_HOSTAPD_SSID_AP_AACN="${WLN_HOSTAPD_SSID_AP}(A/AC/N)"
WLN_HOSTAPD_SSID_RT="LTPP3G2-RT"
WLN_HOSTAPD_SSID_RT_B="${WLN_HOSTAPD_SSID_RT}(B)"
WLN_HOSTAPD_SSID_RT_GN="${WLN_HOSTAPD_SSID_RT}(G/N)"
WLN_HOSTAPD_SSID_RT_AACN="${WLN_HOSTAPD_SSID_RT}(A/AC/N)"
WLN_HOSTAPD_WEPDEFAULTKEY_0=0
WLN_HOSTAPD_WEP_KEY64_DEFAULT="1234567890"
WLN_HOSTAPD_WEP_KEY128_DEFAULT="12345678901234567890123456"
WLN_HOSTAPD_WPAMODE_WPA=1
WLN_HOSTAPD_WPAMODE_WPA2=2
WLN_HOSTAPD_WPAMODE_WPA3=3
WLN_HOSTAPD_WPA_PASSPHRASE_DEFAULT="p@ssw0rd"
WLN_HOSTAPD_WPA_MGMTALG_WPA_PSK="WPA-PSK"
WLN_HOSTAPD_WPA_MGMTALG_SAE="SAE"
WLN_HOSTAPD_WPA_CYPHER_TKIP="TKIP"
WLN_HOSTAPD_WPA_CYPHER_CCMP="CCMP"
WLN_HOSTAPD_WPA_CYPHER_TKIP_CCMP="TKIP CCMP"
WLN_HOSTAPD_WPA_AUTH_ALGS_WEP="2"   #this number is correct
WLN_HOSTAPD_WPA_AUTH_ALGS_WPA="1"   #this number is correct
WLN_HOSTAPD_WPA_AUTH_ALGS_WEP_WPA="3"
WLN_HOSTAPD_WPA_MACADDR_ACL_ACCEPT="0"
WLN_HOSTAPD_WPA_MACADDR_ACL_DENY="1"
WLN_HOSTAPD_WPA_MACADDR_ACL_RADIUSSERVER="2"
WLN_HOSTAPD_IGNORE_BROADCAST_SSID_VISIBLE="0"
WLN_HOSTAPD_IGNORE_BROADCAST_SSID_HIDDEN="2"

#---MACROS: INTERFACES
WLN_BR0="br0"
WLN_ETH0="eth0"
WLN_ETH1="eth1"
WLN_LOOPBACK="lo"
WLN_WLAN0="wlan0"

#---MACROS: IPV4
WLN_IPV4_DEFAULT="1.2.0.1"
WLN_IPV4_GATEWAY_DEFAULT="0.0.0.0"
WLN_IPV4_LOCALHOST="127.0.0.1"
WLN_IPV4_NETMASK_DEFAULT="255.255.255.0"
WLN_IPV4_CIDR_BITS_PER_SEGMENT=8
WLN_IPV4_CIDR_PREFIX_24=24
WLN_IPV4_CIDR_PREFIX_31=31
WLN_IPV4_CIDR_PREFIX_32=32
WLN_IPV4_MIN=0
WLN_IPV4_MAX=255
WLN_IPV4_NUMOF_DOTS_MAX=3
WLN_IPV4_NUMOF_SEGMENTS_MAX=4
WLN_IPV4_SUBNET_LOWERBOUND_MINVAL=1
WLN_IPV4_SUBNET_UPPERBOUND_MAXVAL=254

#---MACROS: IPV6
WLN_IPV6_DEFAULT="1:2::1"
WLN_IPV6_GATEWAY_DEFAULT="0::0"
WLN_IPV6_SUBNET_LOWERBOUND_MINVAL="0000"
WLN_IPV6_SUBNET_UPPERBOUND_MAXVAL="ffff"

WLN_IPV6_TRAILCHAR_0="0"
WLN_IPV6_TRAILCHAR_1="1"
WLN_IPV6_TRAILCHAR_3="3"
WLN_IPV6_TRAILCHAR_7="7"
WLN_IPV6_TRAILCHAR_F="f"

WLN_IPV6_ADDRLEN_IN_BITS=128
WLN_IPV6_ONEHEXLEN_IN_BITS=4
WLN_IPV6_ONEHEXLEN_IN_DEC=16
WLN_IPV6_ONEBLOCKLEN_IN_HEXES=4
WLN_IPV6_ONEBLOCKLEN_IN_BITS=$(( WLN_IPV6_ONEHEXLEN_IN_BITS * WLN_IPV6_ONEBLOCKLEN_IN_HEXES ))
WLN_IPV6_ADDRLEN_IN_HEXES=$(( WLN_IPV6_ADDRLEN_IN_BITS/WLN_IPV6_ONEHEXLEN_IN_BITS))
WLN_IPV6_ADDRLEN_IN_BLOCKS=$(( WLN_IPV6_ADDRLEN_IN_BITS/WLN_IPV6_ONEBLOCKLEN_IN_BITS ))

WLN_IPV6_CIDR_DEFAULT=64
WLN_IPV6_CIDR_112=112

WLN_IPV6_BOGUS_STRVAL=${WLN_EMPTYSTRING}
WLN_IPV6_BOGUS_INTVAL_255=255    #this is an invalid value

#---MACROS: MODULE
WLN_BCMDHD="bcmdhd"

#---MACROS: NETPLAN
WLN_AP_BRIF_LIST="${WLN_WLAN0},${WLN_ETH0},${WLN_ETH1}"
WLN_RT_BRIF_LIST="${WLN_WLAN0}"
WLN_BSSID_000000="0:0:0:0:0:0"

#---MACROS: NUMERIC
WLN_EXITCODE_99=99

WLN_NUM_0=0
WLN_NUM_1=1
WLN_NUM_2=2
WLN_NUM_3=3
WLN_NUM_4=4

WLN_MOD_644=644
WLN_MOD_755=755
WLN_MOD_776=776

WLN_PI=3.141592654

WLN_PORT_53=53
WLN_PORT_67=67
WLN_PORT_68=68
WLN_PORT_547=547
WLN_PORT_5553=5553

WLN_APTGET_LOCK_TIMEOUT=3

#---MACROS: PATH
WLN_BIN="bin"
WLN_BRIF="brif"
WLN_CONFIG_TXT="config.txt"
WLN_CONFIG_TXT_AUTORECONNECTONBOOT="${WLN_CONFIG_TXT}.autoreconnectonboot"
WLN_CONFIG_TXT_CURRENT="${WLN_CONFIG_TXT}.current"
WLN_DATA="data"
WLN_DEFAULT="default"
WLN_DNSMASQ="dnsmasq"
WLN_FIRMWARE="firmware"
WLN_HOSTAPD="hostapd"
WLN_HOSTAPD_NG="hostapd-ng"
WLN_HOSTAPD_NG_AUTORECOVER="hostapd-ng-autorecover"
WLN_INTFSTATES_CTX="intfstates_ctx"
WLN_IPTABLES="iptables"
WLN_IPTABLES_RESTORE="iptables-restore"
WLN_IP6TABLES="ip6tables"
WLN_IP6TABLES_RESTORE="ip6tables-restore"
WLN_LIB="lib"
WLN_LOCAL="local"
WLN_LOG="log"
WLN_NETPLAN="netplan"
WLN_IPTABLES_RESTORE="iptables-restore"
WLN_IPTABLES_SAVE="iptables-save"
WLN_IPTABLES_RULES_V4="rules.v4"
WLN_IPTABLES_RULES_V4_AUTORECONNECTONBOOT="rules.v4.autoreconnectonboot"
WLN_IPTABLES_RULES_V4_CURRENT="rules.v4.current"
WLN_IPTABLES_RULES_V4_ORG="rules.v4.org"
WLN_IP6TABLES_RESTORE="ip6tables-restore"
WLN_IP6TABLES_SAVE="ip6tables-save"
WLN_IP6TABLES_RULES_V6="rules.v6"
WLN_IPTABLES_RULES_V6_ORG="rules.v6.org"
WLN_IPTABLES_RULES_V6_AUTORECONNECTONBOOT="rules.v6.autoreconnectonboot"
WLN_IPTABLES_RULES_V6_CURRENT="rules.v6.current"
WLN_NTIOS_WLN_AUTORECONNECTONBOOT="ntios-wln-autoreconnectonboot"
WLN_NTIOS_WLN_AUTORECONNECTONBOOT_RUNATLOGIN="${WLN_NTIOS_WLN_AUTORECONNECTONBOOT}-runatlogin"
WLN_NTIOS_WLN_AUTORESETCONNECT="ntios-wln-autoresetconnect"
WLN_NTIOS_WLN_RELOADCONNECT="ntios-wln-reloadconnect"
WLN_NTIOS_WLN_RESETCONNECT="ntios-wln-resetconnect"
WLN_PROFILED="profile.d"
WLN_SHUTDOWN_TARGET_WANTS="shutdown.target.wants"
WLN_SYSCTL="sysctl"
WLN_SYSTEM="system"
WLN_SYSTEMD="systemd"
WLN_STATISTICS="statistics"
WLN_TIBBO="tibbo"
WLN_TXBYTES="tx_bytes"
WLN_STATISTICS_TXBYTES="${WLN_STATISTICS}/${WLN_TXBYTES}"
WLN_WIFI_POWERSAVE_OFF="wifi-powersave-off"
WLN_WPA_SUPPLICANT="wpa_supplicant"
WLN_WPA_SUPPLICANT_DAEMON="wpa_supplicant_daemon"
WLN_WPA_SUPPLICANT_NETPLAN_DAEMON_KILL="wpa_supplicant_netplan_daemon_kill"
WLN_WPA_WLAN0="wpa-wlan0"
WLN_NET_YAML="*.yaml"
WLN_WLAN_YAML="wlan.yaml"
WLN_WLAN_YAML_AUTORECONNECTONBOOT="wlan.yaml.autoreconnectonboot"
WLN_WLAN_YAML_CURRENT="wlan.yaml.current"
WLN_WLAN_YAML_WPASUPPLICANT="wlan.yaml.wpasupplicant"
WLN_WLN="wln"

WLN_DNSMASQ_CONF="${WLN_DNSMASQ}.conf"
WLN_DNSMASQ_CONF_AUTORECONNECTONBOOT="${WLN_DNSMASQ_CONF}.autoreconnectonboot"
WLN_DNSMASQ_CONF_CURRENT="${WLN_DNSMASQ_CONF}.current"
WLN_DNSMASQ_SRV="${WLN_DNSMASQ}.service"
WLN_HOSTAPD_SRV="${WLN_HOSTAPD}.service"
WLN_HOSTAPD_CONF="${WLN_HOSTAPD}.conf"
WLN_HOSTAPD_CONF_AUTORECONNECTONBOOT="${WLN_HOSTAPD_CONF}.autoreconnectonboot"
WLN_HOSTAPD_CONF_CURRENT="${WLN_HOSTAPD_CONF}.current"
WLN_HOSTAPD_LOG="${WLN_HOSTAPD}.log"
WLN_HOSTAPD_RUN="${WLN_HOSTAPD}.run"
WLN_HOSTAPD_NG_SRV="${WLN_HOSTAPD_NG}.service"
WLN_HOSTAPD_NG_SRV_AUTORECONNECTONBOOT="${WLN_HOSTAPD_NG_SRV}.autoreconnectonboot"
WLN_HOSTAPD_NG_SRV_CURRENT="${WLN_HOSTAPD_NG_SRV}.current"
WLN_HOSTAPD_NG_SH="${WLN_HOSTAPD_NG}.sh"
WLN_HOSTAPD_NG_AUTORECOVER_SRV="${WLN_HOSTAPD_NG_AUTORECOVER}.service"
WLN_HOSTAPD_NG_AUTORECOVER_SH="${WLN_HOSTAPD_NG_AUTORECOVER}.sh"
WLN_HOSTAPD_NG_AUTORECOVER_TIMER="${WLN_HOSTAPD_NG_AUTORECOVER}.timer"
WLN_INTFSTATES_CTX_DAT="${WLN_INTFSTATES_CTX}.dat"
WLN_INTFSTATES_CTX_INIT_DAT="${WLN_INTFSTATES_CTX}.init.dat"
WLN_IPTABLES_SRV="${WLN_IPTABLES}.service"
WLN_IP6TABLES_SRV="${WLN_IP6TABLES}.service"

WLN_NTIOS_WLN_AUTORECONNECTONBOOT_LOG="${WLN_NTIOS_WLN_AUTORECONNECTONBOOT}.log"
WLN_NTIOS_WLN_AUTORECONNECTONBOOT_SRV="${WLN_NTIOS_WLN_AUTORECONNECTONBOOT}.service"
WLN_NTIOS_WLN_AUTORECONNECTONBOOT_RUNATLOGIN_SH="${WLN_NTIOS_WLN_AUTORECONNECTONBOOT_RUNATLOGIN}.sh"
WLN_NTIOS_WLN_AUTORECONNECTONBOOT_SH="${WLN_NTIOS_WLN_AUTORECONNECTONBOOT}.sh"
WLN_NTIOS_WLN_AUTORESETCONNECT_SH="${WLN_NTIOS_WLN_AUTORESETCONNECT}.sh"
WLN_NTIOS_WLN_RELOADCONNECT_SRV="${WLN_NTIOS_WLN_RELOADCONNECT}.service"
WLN_NTIOS_WLN_RESETCONNECT_SRV="${WLN_NTIOS_WLN_RESETCONNECT}.service"

WLN_SYSCTL_CONF="${WLN_SYSCTL}.conf"
WLN_WIFI_POWERSAVE_OFF_SRV="${WLN_WIFI_POWERSAVE_OFF}.service"
WLN_WIFI_POWERSAVE_OFF_SH="${WLN_WIFI_POWERSAVE_OFF}.sh"
WLN_WIFI_POWERSAVE_OFF_TIMER="${WLN_WIFI_POWERSAVE_OFF}.timer"
WLN_WPA_SUPPLICANT_CONF="${WLN_WPA_SUPPLICANT}.conf"
WLN_WPA_SUPPLICANT_SRV="${WLN_WPA_SUPPLICANT}.service"
WLN_WPA_SUPPLICANT_DAEMON_SRV="${WLN_WPA_SUPPLICANT_DAEMON}.service"
WLN_WPA_SUPPLICANT_DAEMON_SH="${WLN_WPA_SUPPLICANT_DAEMON}.sh"
WLN_WPA_SUPPLICANT_NETPLAN_DAEMON_KILL_SRV="${WLN_WPA_SUPPLICANT_NETPLAN_DAEMON_KILL}.service"
WLN_WPA_SUPPLICANT_NETPLAN_DAEMON_KILL_SH="${WLN_WPA_SUPPLICANT_NETPLAN_DAEMON_KILL}.sh"
WLN_WPA_WLAN0_CONF="${WLN_WPA_WLAN0}.conf"
WLN_WPA_WLAN0_LOG="${WLN_WPA_WLAN0}.log"

WLN_ETC_DIR="/etc"
WLN_RUN_DIR="/run"
WLN_SBIN_DIR="/sbin"
WLN_TMP_DIR="/tmp"
WLN_USR_DIR="/usr"
WLN_SYS_CLASS_NET_DIR="/sys/class/net"

WLN_ETC_DEFAULT_DIR="${WLN_ETC_DIR}/${WLN_DEFAULT}"
WLN_ETC_FIRMWARE_DIR="${WLN_ETC_DIR}/${WLN_FIRMWARE}"
WLN_ETC_HOSTAPD_DIR="${WLN_ETC_DIR}/${WLN_HOSTAPD}"
WLN_ETC_IPTABLES_DIR="${WLN_ETC_DIR}/${WLN_IPTABLES}"
WLN_ETC_IP6TABLES_DIR="${WLN_ETC_DIR}/${WLN_IP6TABLES}"
WLN_ETC_NETPLAN_DIR="${WLN_ETC_DIR}/${WLN_NETPLAN}"
WLN_ETC_PROFILED_DIR="${WLN_ETC_DIR}/${WLN_PROFILED}"
WLN_ETC_SYSTEMD_SYSTEM_DIR="${WLN_ETC_DIR}/${WLN_SYSTEMD}/${WLN_SYSTEM}"
WLN_ETC_SYSTEMD_SYSTEM_SHUTDOWN_TARGET_WANTS_DIR="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_SHUTDOWN_TARGET_WANTS}"
WLN_ETC_TIBBO_DIR="${WLN_ETC_DIR}/${WLN_TIBBO}"
WLN_ETC_TIBBO_DATA_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_DATA}"
WLN_ETC_TIBBO_DATA_WLN_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_DATA}/${WLN_WLN}"
WLN_ETC_TIBBO_DNSMASQ_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_DNSMASQ}"
WLN_ETC_TIBBO_DNSMASQ_WLN_DIR="${WLN_ETC_TIBBO_DNSMASQ_DIR}/${WLN_WLN}"
WLN_ETC_TIBBO_FIRMWARE_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_FIRMWARE}"
WLN_ETC_TIBBO_FIRMWARE_WLN_DIR="${WLN_ETC_TIBBO_FIRMWARE_DIR}/${WLN_WLN}"
WLN_ETC_TIBBO_HOSTAPD_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_HOSTAPD}"
WLN_ETC_TIBBO_HOSTAPD_WLN_DIR="${WLN_ETC_TIBBO_HOSTAPD_DIR}/${WLN_WLN}"
WLN_ETC_TIBBO_IPTABLES_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_IPTABLES}"
WLN_ETC_TIBBO_IPTABLES_WLN_DIR="${WLN_ETC_TIBBO_IPTABLES_DIR}/${WLN_WLN}"
WLN_ETC_TIBBO_IP6TABLES_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_IP6TABLES}"
WLN_ETC_TIBBO_IP6TABLES_WLN_DIR="${WLN_ETC_TIBBO_IP6TABLES_DIR}/${WLN_WLN}"
WLN_ETC_TIBBO_LOG_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_LOG}"
WLN_ETC_TIBBO_LOG_WLN_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_LOG}/${WLN_WLN}"
WLN_ETC_TIBBO_NETPLAN_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_NETPLAN}"
WLN_ETC_TIBBO_NETPLAN_WLN_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_NETPLAN}/${WLN_WLN}"
WLN_ETC_TIBBO_PROFILED_WLN_DIR="${WLN_ETC_TIBBO_DIR}/${WLN_PROFILED}/${WLN_WLN}"

WLN_ETC_WLN_DIR="${WLN_ETC_DIR}/${WLN_WLN}"
WLN_RUN_NETPLAN_DIR="${WLN_RUN_DIR}/${WLN_NETPLAN}"
WLN_SYS_CLASS_NET_BR0_BRIF_DIR=${WLN_SYS_CLASS_NET_DIR}/${WLN_BR0}/${WLN_BRIF}

WLN_USR_LIB_SYSTEMD_SYSTEM_DIR="${WLN_USR_DIR}/${WLN_LIB}/${WLN_SYSTEMD}/${WLN_SYSTEM}/"
WLN_USR_LOCAL_BIN_DIR="${WLN_USR_DIR}/${WLN_LOCAL}/${WLN_BIN}"
WLN_USR_SBIN_DIR="${WLN_USR_DIR}${WLN_SBIN_DIR}"

WLN_DNSMASQ_CONF_FPATH="${WLN_ETC_DIR}/${WLN_DNSMASQ_CONF}"
WLN_DNSMASQ_CONF_AUTORECONNECTONBOOT_FPATH="${WLN_ETC_TIBBO_DNSMASQ_WLN_DIR}/${WLN_DNSMASQ_CONF_AUTORECONNECTONBOOT}"
WLN_DNSMASQ_CONF_CURRENT_FPATH="${WLN_ETC_TIBBO_DNSMASQ_WLN_DIR}/${WLN_DNSMASQ_CONF_CURRENT}"
WLN_DNSMASQ_SERVICE_FPATH="${WLN_USR_LIB_SYSTEMD_SYSTEM_DIR}/${WLN_DNSMASQ_SRV}"

WLN_HOSTAPD_SERVICE_FPATH="${WLN_USR_LIB_SYSTEMD_SYSTEM_DIR}/${WLN_HOSTAPD_SRV}"

WLN_HOSTAPD_NG_SERVICE_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_HOSTAPD_NG_SRV}"
WLN_HOSTAPD_NG_SERVICE_AUTORECONNECTONBOOT_FPATH="${WLN_ETC_TIBBO_HOSTAPD_WLN_DIR}/${WLN_HOSTAPD_NG_SRV_AUTORECONNECTONBOOT}"
WLN_HOSTAPD_NG_SERVICE_CURRENT_FPATH="${WLN_ETC_TIBBO_HOSTAPD_WLN_DIR}/${WLN_HOSTAPD_NG_SRV_CURRENT}"
WLN_HOSTAPD_NG_SH_FPATH="${WLN_USR_LOCAL_BIN_DIR}/${WLN_HOSTAPD_NG_SH}"

WLN_HOSTAPD_NG_AUTORECOVER_SERVICE_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_HOSTAPD_NG_AUTORECOVER_SRV}"
WLN_HOSTAPD_NG_AUTORECOVER_SH_FPATH="${WLN_USR_LOCAL_BIN_DIR}/${WLN_HOSTAPD_NG_AUTORECOVER_SH}"
WLN_HOSTAPD_NG_AUTORECOVER_TIMER_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_HOSTAPD_NG_AUTORECOVER_TIMER}"

WLN_FIRMWARE_CONFIG_TXT_FPATH="${WLN_ETC_FIRMWARE_DIR}/${WLN_CONFIG_TXT}"
WLN_FIRMWARE_CONFIG_TXT_AUTORECONNECTONBOOT_FPATH="${WLN_ETC_TIBBO_FIRMWARE_WLN_DIR}/${WLN_CONFIG_TXT_AUTORECONNECTONBOOT}"
WLN_FIRMWARE_CONFIG_TXT_CURRENT_FPATH="${WLN_ETC_TIBBO_FIRMWARE_WLN_DIR}/${WLN_CONFIG_TXT_CURRENT}"

WLN_DEFAULT_HOSTAPD_FPATH="${WLN_ETC_DEFAULT_DIR}/${WLN_HOSTAPD}"
WLN_HOSTAPD_CONF_FPATH="${WLN_ETC_HOSTAPD_DIR}/${WLN_HOSTAPD_CONF}"
WLN_HOSTAPD_CONF_AUTORECONNECTONBOOT_FPATH="${WLN_ETC_TIBBO_HOSTAPD_WLN_DIR}/${WLN_HOSTAPD_CONF_AUTORECONNECTONBOOT}"
WLN_HOSTAPD_CONF_CURRENT_FPATH="${WLN_ETC_TIBBO_HOSTAPD_WLN_DIR}/${WLN_HOSTAPD_CONF_CURRENT}"
WLN_HOSTAPD_LOG_FPATH="${WLN_ETC_TIBBO_LOG_WLN_DIR}/${WLN_HOSTAPD_LOG}"
WLN_HOSTAPD_RUN_FPATH="${WLN_RUN_DIR}/${WLN_HOSTAPD_RUN}"
WLN_HOSTAPD_EXEC_FPATH="${WLN_USR_SBIN_DIR}/${WLN_HOSTAPD}"

WLN_SED_NOTATION_ETC_HOSTAPD_DIR="\\${WLN_ETC_DIR}\\/${WLN_HOSTAPD}"
WLN_SED_NOTATION_ETC_HOSTAPD_HOSTAPD_CONF_FPATH="${WLN_SED_NOTATION_ETC_HOSTAPD_DIR}\\/${WLN_HOSTAPD_CONF}"

WLN_INTFSTATES_CTX_DAT_FPATH="${WLN_ETC_TIBBO_DATA_WLN_DIR}/${WLN_INTFSTATES_CTX_DAT}"
WLN_INTFSTATES_CTX_INIT_DAT_FPATH="${WLN_ETC_TIBBO_DATA_WLN_DIR}/${WLN_INTFSTATES_CTX_INIT_DAT}"

WLN_IPTABLES_RESTORE_FPATH="${WLN_SBIN_DIR}/${WLN_IPTABLES_RESTORE}"
WLN_IPTABLES_SAVE_FPATH="${WLN_SBIN_DIR}/${WLN_IPTABLES_SAVE}"
WLN_IPTABLES_RULES_V4_FPATH="${WLN_ETC_IPTABLES_DIR}/${WLN_IPTABLES_RULES_V4}"
WLN_IPTABLES_RULES_V4_AUTORECONNECTONBOOT_FPATH="${WLN_ETC_TIBBO_IPTABLES_WLN_DIR}/${WLN_IPTABLES_RULES_V4_AUTORECONNECTONBOOT}"
WLN_IPTABLES_RULES_V4_CURRENT_FPATH="${WLN_ETC_TIBBO_IPTABLES_WLN_DIR}/${WLN_IPTABLES_RULES_V4_CURRENT}"
WLN_IPTABLES_RULES_V4_ORG_FPATH="${WLN_ETC_TIBBO_IPTABLES_WLN_DIR}/${WLN_IPTABLES_RULES_V4_ORG}"
WLN_IPTABLES_SERVICE_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_IPTABLES_SRV}"

WLN_IP6TABLES_RESTORE_FPATH="${WLN_SBIN_DIR}/${WLN_IP6TABLES_RESTORE}"
WLN_IP6TABLES_SAVE_FPATH="${WLN_SBIN_DIR}/${WLN_IP6TABLES_SAVE}"
WLN_IP6TABLES_RULES_V6_FPATH="${WLN_ETC_IP6TABLES_DIR}/${WLN_IP6TABLES_RULES_V6}"
WLN_IP6TABLES_RULES_V6_AUTORECONNECTONBOOT_FPATH="${WLN_ETC_TIBBO_IP6TABLES_WLN_DIR}/${WLN_IPTABLES_RULES_V6_AUTORECONNECTONBOOT}"
WLN_IP6TABLES_RULES_V6_CURRENT_FPATH="${WLN_ETC_TIBBO_IP6TABLES_WLN_DIR}/${WLN_IPTABLES_RULES_V6_CURRENT}"
WLN_IP6TABLES_RULES_V6_ORG_FPATH="${WLN_ETC_TIBBO_IP6TABLES_WLN_DIR}/${WLN_IPTABLES_RULES_V6_ORG}"
WLN_IP6TABLES_SERVICE_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_IP6TABLES_SRV}"

WLN_NTIOS_WLN_AUTORECONNECTONBOOT_LOG_FPATH="${WLN_ETC_TIBBO_LOG_WLN_DIR}/${WLN_NTIOS_WLN_AUTORECONNECTONBOOT_LOG}"
WLN_NTIOS_WLN_AUTORECONNECTONBOOT_SRV_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_NTIOS_WLN_AUTORECONNECTONBOOT_SRV}"
WLN_NTIOS_WLN_AUTORECONNECTONBOOT_RUNATLOGIN_SH_SRC_FPATH="${WLN_ETC_TIBBO_PROFILED_WLN_DIR}/${WLN_NTIOS_WLN_AUTORECONNECTONBOOT_RUNATLOGIN_SH}"
WLN_NTIOS_WLN_AUTORECONNECTONBOOT_RUNATLOGIN_SH_DST_FPATH="${WLN_ETC_PROFILED_DIR}/${WLN_NTIOS_WLN_AUTORECONNECTONBOOT_RUNATLOGIN_SH}"
WLN_NTIOS_WLN_AUTORESETCONNECT_SH_FPATH="${WLN_USR_LOCAL_BIN_DIR}/${WLN_NTIOS_WLN_AUTORESETCONNECT_SH}"
WLN_NTIOS_WLN_RELOADCONNECT_SRV_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_NTIOS_WLN_RELOADCONNECT_SRV}"
WLN_NTIOS_WLN_RELOADCONNECT_SRV_SIMLINK_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_SHUTDOWN_TARGET_WANTS_DIR}/${WLN_NTIOS_WLN_RELOADCONNECT_SRV}"
WLN_NTIOS_WLN_RESETCONNECT_SRV_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_NTIOS_WLN_RESETCONNECT_SRV}"
WLN_NTIOS_WLN_RESETCONNECT_SRV_SIMLINK_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_SHUTDOWN_TARGET_WANTS_DIR}/${WLN_NTIOS_WLN_RESETCONNECT_SRV}"

WLN_SYSCTL_CONF_FPATH="${WLN_ETC_DIR}/${WLN_SYSCTL_CONF}"

WLN_WIFI_POWERSAVE_OFF_SERVICE_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_WIFI_POWERSAVE_OFF_SRV}"
WLN_WIFI_POWERSAVE_OFF_SH_FPATH="${WLN_USR_LOCAL_BIN_DIR}/${WLN_WIFI_POWERSAVE_OFF_SH}"
WLN_WIFI_POWERSAVE_OFF_TIMER_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_WIFI_POWERSAVE_OFF_TIMER}"

WLN_WPA_SUPPLICANT_CONF_FPATH="${WLN_ETC_DIR}/${WLN_WPA_SUPPLICANT_CONF}"
WLN_WPA_SUPPLICANT_SERVICE_FPATH="${WLN_USR_LIB_SYSTEMD_SYSTEM_DIR}/${WLN_WPA_SUPPLICANT_SRV}"
WLN_WPA_SUPPLICANT_DAEMON_SERVICE_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_WPA_SUPPLICANT_DAEMON_SRV}"
WLN_WPA_SUPPLICANT_DAEMON_SH_FPATH="${WLN_USR_LOCAL_BIN_DIR}/${WLN_WPA_SUPPLICANT_DAEMON_SH}"
WLN_WPA_SUPPLICANT_NETPLAN_DAEMON_KILL_SERVICE_FPATH="${WLN_ETC_SYSTEMD_SYSTEM_DIR}/${WLN_WPA_SUPPLICANT_NETPLAN_DAEMON_KILL_SRV}"
WLN_WPA_SUPPLICANT_NETPLAN_DAEMON_KILL_SH_FPATH="${WLN_USR_LOCAL_BIN_DIR}/${WLN_WPA_SUPPLICANT_NETPLAN_DAEMON_KILL_SH}"
WLN_WPA_SUPPLICANT_EXEC_FPATH="${WLN_SBIN_DIR}/${WLN_WPA_SUPPLICANT}"
WLN_WPA_WLAN0_CONF_FPATH="${WLN_RUN_NETPLAN_DIR}/${WLN_WPA_WLAN0_CONF}"
WLN_WPA_WLAN0_LOG_FPATH="${WLN_ETC_TIBBO_LOG_WLN_DIR}/${WLN_WPA_WLAN0_LOG}"

WLN_NET_YAML_FPATH=${WLN_ETC_NETPLAN_DIR}/${WLN_NET_YAML}   #NOT required for c++ wln-object
WLN_WLAN_YAML_FPATH=${WLN_ETC_NETPLAN_DIR}/${WLN_WLAN_YAML}
WLN_WLAN_YAML_AUTORECONNECTONBOOT_FPATH=${WLN_ETC_TIBBO_NETPLAN_WLN_DIR}/${WLN_WLAN_YAML_AUTORECONNECTONBOOT}
WLN_WLAN_YAML_CURRENT_FPATH=${WLN_ETC_TIBBO_NETPLAN_WLN_DIR}/${WLN_WLAN_YAML_CURRENT}

#---MACROS: PATTERN
WLN_PATTERN_ACCEPT="ACCEPT"
WPL_PATTERN_ACCESS_POINTS="access-points"
WLN_PATTERN_ASTERISK_FILTER="\\*filter"
WLN_PATTERN_ASTERISK_NAT="\\*nat"
WLN_PATTERN_BRIDGES="bridges"
WLN_PATTERN_BROADCAST="BROADCAST"
WLN_PATTERN_BSS_SPACE="BSS "
WLN_PATTERN_CAPABILITY_COLONSPACE="capability: "
WLN_PATTERN_CCODE="ccode"
# WLN_PATTERN_CHANNEL="Channel"
WLN_PATTERN_CHANNEL_COLONSPACE="channel: "
WLN_PATTERN_CHANNEL_SPACE="channel "
WLN_PATTERN_COMMIT="COMMIT"
WLN_PATTERN_DOWN="DOWN"
WLN_PATTERN_DSPARAMETERSET_COLONSPACE="DS Parameter set: "
WLN_PATTERN_ESS="ESS"
WLN_PATTERN_FAILED_TO_SET_BEACON_PARAMETERS="Failed to set beacon parameters"
WLN_PATTERN_GLOBAL="global"
WLN_PATTERN_GREP="grep"
WLN_PATTERN_IBSS="IBSS"
WLN_PATTERN_INET="inet"
WLN_PATTERN_INET6="inet6"
WLN_PATTERN_INTERFACES="interfaces"
WLN_PATTERN_NET_IPV4_IP_FORWARD_ENABLED="net.ipv4.ip_forward=1"
WLN_PATTERN_NET_IPV6_CONF_ALL_FORWARDING_ENABLED="net.ipv6.conf.all.forwarding=1"
WLN_PATTERN_NL80211_KERNEL_REPORTS_KEY_NOT_ALLOWED="nl80211: kernel reports: key not allowed"
WLN_PATTERN_PID="PID"
WLN_PATTERN_PRIMARY_CHANNEL_COLONSPACE="primary channel: "
WLN_PATTERN_SIGNAL="signal"
WLN_PATTERN_SSID="ssid"
WLN_PATTERN_SSID_COLONSPACE="SSID: "
WLN_PATTERN_UNKNOWN="UNKNOWN"
WLN_PATTERN_UP="UP"
WLN_PATTERN_WLAN0_CLTR_EVENT_CONNECTED="${WLN_WLAN0}: CTRL-EVENT-CONNECTED"
WLN_PATTERN_WPA_SUPPLICANT="${WLN_WPA_SUPPLICANT}"
WLN_SED_PATTERN_DAEMON_CONF_OLD="#DAEMON_CONF\\=\"\""
WLN_SED_PATTERN_DAEMON_CONF_NEW="DAEMON_CONF\\=${WLN_SED_NOTATION_ETC_HOSTAPD_HOSTAPD_CONF_FPATH}"

#---MACROS: PRINT
WLN_PRINTMSG_EMPTYSTRING="<Empty String>"

WLN_PRINTMSG_STATUS=":-->${WLN_ORANGE}STATUS${WLN_RESETCOLOR}"

WLN_PRINTMSG_ACCEPTED="${WLN_LIGHTGREEN}ACCEPTED${WLN_RESETCOLOR}"
WLN_PRINTMSG_REJECTED="${WLN_SOFLIGHTRED}REJECTED${WLN_RESETCOLOR}"

WLN_PRINTMSG_DISABLED="${WLN_SOFLIGHTRED}DISABLED${WLN_RESETCOLOR}"
WLN_PRINTMSG_ENABLED="${WLN_LIGHTGREEN}ENABLED${WLN_RESETCOLOR}"

WLN_PRINTMSG_START="${WLN_LIGHTGREEN}START${WLN_RESETCOLOR}"
WLN_PRINTMSG_STOP="${WLN_SOFLIGHTRED}STOP${WLN_RESETCOLOR}"

WLN_PRINTMSG_ALREADYDONE="${WLN_YELLOW}ALREADY DONE${WLN_RESETCOLOR}"
WLN_PRINTMSG_DONE="${WLN_YELLOW}DONE${WLN_RESETCOLOR}"
WLN_PRINTMSG_FAILED="${WLN_SOFLIGHTRED}FAILED${WLN_RESETCOLOR}"

WLN_PRINTMSG_COMPLETED="${WLN_LIGHTBLUE}COMPLETED${WLN_RESETCOLOR}"
WLN_PRINTMSG_CREATING="${WLN_LIGHTGREEN}CREATING...${WLN_RESETCOLOR}"
WLN_PRINTMSG_CREATE_AND_TRIGGER="${WLN_LIGHTGREEN}CREATE${WLN_RESETCOLOR}&${WLN_LIGHTBLUE}TRIGGER${WLN_RESETCOLOR}..."
WLN_PRINTMSG_ENABLING="${WLN_LIGHTBLUE}ENABLING...${WLN_RESETCOLOR}"
WLN_PRINTMSG_IN_PROGRESS="${WLN_LIGHTBLUE}IN PROGRESS...${WLN_RESETCOLOR}"
WLN_PRINTMSG_INSTALLING="${WLN_LIGHTBLUE}INSTALLING...${WLN_RESETCOLOR}"
WLN_PRINTMSG_NO="${WLN_SOFLIGHTRED}NO${WLN_RESETCOLOR}"
WLN_PRINTMSG_NOT="${WLN_SOFLIGHTRED}NOT${WLN_RESETCOLOR}"
WLN_PRINTMSG_NOT_PRESENT="${WLN_PRINTMSG_NOT} PRESENT..."
WLN_PRINTMSG_NOT_SET="${WLN_PRINTMSG_NOT} SET..."
WLN_PRINTMSG_DISABLESTOP="${WLN_LIGHTBLUE}STOP${WLN_RESETCOLOR}&${WLN_LIGHTBLUE}DISABLE${WLN_RESETCOLOR}..."
WLN_PRINTMSG_REMOVING="${WLN_SOFLIGHTRED}REMOVING...${WLN_RESETCOLOR}"
WLN_PRINTMSG_STARTING="${WLN_LIGHTBLUE}STARTING...${WLN_RESETCOLOR}"
WLN_PRINTMSG_UPDATING="${WLN_LIGHTBLUE}UPDATING${WLN_RESETCOLOR}..."
WLN_PRINTMSG_VALIDATING="${WLN_LIGHTBLUE}VALIDATING${WLN_RESETCOLOR}..."

WLN_PRINTMSG_TRUE="${WLN_LIGHTGREEN}True${WLN_RESETCOLOR}"
WLN_PRINTMSG_FALSE="${WLN_SOFLIGHTRED}False${WLN_RESETCOLOR}"

WLN_PRINTMSG_SETWEP="${WLN_LIGHTGREY}SetWEP${WLN_RESETCOLOR}"
WLN_PRINTMSG_SETWPA="${WLN_LIGHTGREY}SetWPA${WLN_RESETCOLOR}"



#---MACROS: REGULAR EXPRESSIONS
WLN_COLON=":"
WLN_DOUBLECOLON="::"
WLN_DOT="."

#---MACROS: SED
WLN_SED_SIXSPACES_ESCAPED="\ \ \ \ \ \ "
WLN_SED_EIGHTSPACES_ESCAPED="\ \ \ \ \ \ \ \ "
WLN_SED_SIXSPACES_ESCAPED_WITH_THREE_BACKSLASHES="\\\ \\\ \\\ \\\ \\\ \\\ "

#---MACROS: SOFTWARE
WLN_BRIDGE_UTILS="bridge-utils"
WLN_DNSMASQ="dnsmasq"
WLN_HOSTAPD="hostapd"
WLN_IW="iw"
WLN_WIRELESSTOOLS="wireless-tools"
WLN_WPASUPPLICANT="wpasupplicant"

#---MACROS: (EMPTY) SPACES
WLN_EMPTYSTRING=""
WLN_TWOSPACES="  "
WLN_FOURSPACES="    "
WLN_SIXSPACES="      "
WLN_EIGHTSPACES="        "
WLN_TENSPACES="          "

#---MACROS: STATES
WLN_ACTIVE="active"
WLN_INACTIVE="inactive"
WLN_DISABLED="disabled"
WLN_ENABLED="enabled"
WLN_UNKNOWN="unknown"

#---MACROS: STRINGS
WLN_HIDDEN="<HIDDEN>"
WLN_NA="n/a"

#---MACROS: DEV
WLN_DEV_TTYS0="/dev/ttyS0"

#---MACROS: WIFI
WLN_WEPKEY64LEN_MAX=10
WLN_WEPKEY128LEN_MAX=26

WLN_WPAKEY_PHRASELEN_MIN=8
WLN_WPAKEY_PHRASELEN_MAX=63

WLN_WIFI_CHANNEL_2G_DEFAULT=1
WLN_WIFI_CHANNEL_2G_UPPERBOUND=14
WLN_WIFI_CHANNEL_5G_DEFAULT=36
WLN_WIFI_CHANNEL_5G_LOWERBOUND=36
WLN_WIFI_CHANNEL_NULL=255
WLN_WIFI_SIGNAL_DBM_MIN=-100
WLN_WIFI_SIGNAL_DBM_MAX=-30
WLN_WIFI_SIGNAL_PERC_MAX=100
WLN_WIFI_SIGNAL_RSSI_MIN=0
WLN_WIFI_SIGNAL_RSSI_MAX=255

WLN_WIFI_CONNECTED="connected"
WLN_WIFI_FAILED_TO_CONNECT="failed-to-connect"
WLN_WIFI_NOT_CONNECTED="not-connected"

WLN_IW_PATTERN_SIGNAL="signal: "
WLN_IW_PATTERN_SSID="SSID: "
WLN_IW_PATTERN_SETCHANNEL="set: channel "

#---STRUCTURES
WLN_intfstates_ctx() {
    WLN_intfstates_ctx__intf=${WLN_EMPTYSTRING}                 #string
    WLN_intfstates_ctx__associationstate=${WLN_EMPTYSTRING}     #pl_wln_tasks
    WLN_intfstates_ctx__autoreconnectonboot=${WLN_EMPTYSTRING}  #no_yes
    WLN_intfstates_ctx__bridge=${WLN_EMPTYSTRING}               #string
    WLN_intfstates_ctx__bssid=${WLN_EMPTYSTRING}                #string
    WLN_intfstates_ctx__bssmode=${WLN_EMPTYSTRING}              #pl_wln_bss_modes
    WLN_intfstates_ctx__cast=${WLN_EMPTYSTRING}                 #pl_wln_wpa_unicast_multicast
    WLN_intfstates_ctx__channel=${WLN_EMPTYSTRING}              #U8
    WLN_intfstates_ctx__cidr=${WLN_EMPTYSTRING}                 #string
    WLN_intfstates_ctx__cidrv6=${WLN_EMPTYSTRING}               #string
    WLN_intfstates_ctx__dhcp=${WLN_EMPTYSTRING}                 #no_yes
    WLN_intfstates_ctx__dhcpv6=${WLN_EMPTYSTRING}               #no_yes
    WLN_intfstates_ctx__dns1=${WLN_EMPTYSTRING}                 #string
    WLN_intfstates_ctx__dns1v6=${WLN_EMPTYSTRING}               #string
    WLN_intfstates_ctx__dns2=${WLN_EMPTYSTRING}                 #string
    WLN_intfstates_ctx__dns2v6=${WLN_EMPTYSTRING}               #string
    WLN_intfstates_ctx__domaincode=${WLN_EMPTYSTRING}           #string
    WLN_intfstates_ctx__driver=${WLN_EMPTYSTRING}               #string
    WLN_intfstates_ctx__enabled=${WLN_EMPTYSTRING}              #no_yes
    WLN_intfstates_ctx__gatewayintf=${WLN_EMPTYSTRING}          #string
    WLN_intfstates_ctx__gatewayip=${WLN_EMPTYSTRING}            #string
    WLN_intfstates_ctx__gatewayipv6=${WLN_EMPTYSTRING}          #string
    WLN_intfstates_ctx__hwmode=${WLN_EMPTYSTRING}               #string
    WLN_intfstates_ctx__ieee80211ac=${WLN_EMPTYSTRING}          #U8
    WLN_intfstates_ctx__ieee80211d=${WLN_EMPTYSTRING}           #U8
    WLN_intfstates_ctx__ieee80211h=${WLN_EMPTYSTRING}           #U8
    WLN_intfstates_ctx__ieee80211n=${WLN_EMPTYSTRING}           #U8
    WLN_intfstates_ctx__ip=${WLN_EMPTYSTRING}                   #string
    WLN_intfstates_ctx__ipv6=${WLN_EMPTYSTRING}                 #string
    WLN_intfstates_ctx__netmask=${WLN_EMPTYSTRING}              #string
    WLN_intfstates_ctx__networkdhcpendip=${WLN_EMPTYSTRING}     #string
    WLN_intfstates_ctx__networkdhcpendipv6=${WLN_EMPTYSTRING}   #string
    WLN_intfstates_ctx__networkdhcpstartip=${WLN_EMPTYSTRING}   #string
    WLN_intfstates_ctx__networkdhcpstartipv6=${WLN_EMPTYSTRING} #string
    WLN_intfstates_ctx__networkdomainname=${WLN_EMPTYSTRING}    #string
    WLN_intfstates_ctx__phymode=${WLN_EMPTYSTRING}              #string

    WLN_intfstates_ctx__scanresultssid=${WLN_EMPTYSTRING}       #string
    WLN_intfstates_ctx__scanresultbssid=${WLN_EMPTYSTRING}      #string
    WLN_intfstates_ctx__scanresultbssmode=${WLN_EMPTYSTRING}    #pl_wln_bss_modes
    WLN_intfstates_ctx__scanresultchannel=${WLN_EMPTYSTRING}    #U8
    WLN_intfstates_ctx__scanresultrssi=${WLN_EMPTYSTRING}       #U8
    WLN_intfstates_ctx__scanresultwpainfo=${WLN_EMPTYSTRING}    #string

    WLN_intfstates_ctx__setwep=${WLN_EMPTYSTRING}               #ACCEPTED/REJECTED
    WLN_intfstates_ctx__setwpa=${WLN_EMPTYSTRING}               #ACCEPTED/REJECTED 
    WLN_intfstates_ctx__ssid=${WLN_EMPTYSTRING}                 #string
    WLN_intfstates_ctx__ssidisvisible=${WLN_EMPTYSTRING}        #no_yes
    WLN_intfstates_ctx__updatetimestamp=${WLN_EMPTYSTRING}      #U32
    WLN_intfstates_ctx__wepkey=${WLN_EMPTYSTRING}               #string
    WLN_intfstates_ctx__wepmode=${WLN_EMPTYSTRING}              #pl_wln_wep_modes    
    WLN_intfstates_ctx__wpaalgorithm=${WLN_EMPTYSTRING}         #pl_wln_wpa_algorithms
    WLN_intfstates_ctx__wpakey=${WLN_EMPTYSTRING}               #string
    WLN_intfstates_ctx__wpamode=${WLN_EMPTYSTRING}              #pl_wln_wpa_modes  
}



#---MAIN SUBROUTINE
main__sub() {
    WLN_intfstates_ctx
}



#---EXECUTE MAIN
main__sub
